version: 0.1
description: build react app

phases:
  install:
    runtime-versions:
      nodejs: latest
  command:
    - echo NodeJS runtime was installed...

  pre-build:
    commands:
      - echo build stage beginnig...

  build:
    commands:
      - echo adding node_modules...
      - npm install
      - echo run react build
      - npm run build
      - echo build complete!

artifacts:
  files:
    - build/*
      